import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
const ROOT="/home/user/current/web";
const T={".html":"text/html",".js":"text/javascript",".css":"text/css"};
const s=createServer(async(rq,rs)=>{const p=new URL(rq.url,"http://x").pathname;const f=join(ROOT,normalize(p));const t=p.endsWith("/")?join(f,"index.html"):f;let b=null;try{b=await readFile(t);}catch{};if(b){rs.writeHead(200,{"Content-Type":T[extname(t)]??"text/plain"});rs.end(b);}else{rs.writeHead(404);rs.end("nf");}});
await new Promise(r=>s.listen(0,r));
const base=`http://127.0.0.1:${s.address().port}`;
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium"});
const page=await b.newPage();
page.on("pageerror",e=>console.log("PAGEERROR:",e.message));
page.on("console",m=>{if(m.type()==="error")console.log("CONSOLE:",m.text())});
page.on("requestfailed",r=>console.log("REQFAIL:",r.url().slice(0,80)));
await page.route("https://fonts.googleapis.com/**",r=>r.fulfill({status:200,contentType:"text/css",body:""}));
await page.route("https://fonts.gstatic.com/**",r=>r.fulfill({status:200,contentType:"font/woff2",body:""}));
await page.addInitScript(`window.__PTP_INSTALL__=(async()=>{const {fakeSupabase}=await import("${base}/tests/fake-supabase.js");const fx=await import("${base}/tests/fixtures.js");window.__PTP_TEST_CLIENT__=fakeSupabase(structuredClone(fx.parentFixtures));})();`);
await page.goto(`${base}/my-ptp/parent/`,{waitUntil:"load"});
await new Promise(r=>setTimeout(r,1500));
console.log("BODY:", (await page.textContent("body")).slice(0,300));
await b.close(); s.close();
