import { chromium } from "playwright";
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
const ROOT="/home/user/current/web/";
const T={".html":"text/html",".js":"text/javascript",".css":"text/css"};
const s=createServer(async(rq,rs)=>{const p=new URL(rq.url,"http://x").pathname;const f=join(ROOT,normalize(p));const t=p.endsWith("/")?join(f,"index.html"):f;
 try{const b=await readFile(t);rs.writeHead(200,{"Content-Type":T[extname(t)]??"text/plain"});rs.end(b);}catch{rs.writeHead(404).end("nf");}});
await new Promise(r=>s.listen(0,r));
const base=`http://127.0.0.1:${s.address().port}`;
const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium"});
const page=await b.newPage({viewport:{width:400,height:900}});
page.on("pageerror",e=>console.log("PAGEERROR:",e.message));
page.on("console",m=>console.log(m.type().toUpperCase()+":",m.text()));
page.on("requestfailed",r=>console.log("REQFAIL:",r.url()));
await page.addInitScript(({b})=>{globalThis.__PTP_FIXTURES__={fixturesName:"publicFixtures",signedIn:false,baseUrl:b};},{b:base});
await page.addInitScript(`window.__PTP_INSTALL__=(async()=>{
  const {fakeSupabase}=await import("${base}/tests/fake-supabase.js");
  const fx=await import("${base}/tests/fixtures.js");
  const src=fx["publicFixtures"];
  const chosen={...structuredClone({session:src.session??null,tables:src.tables}),rpc:src.rpc};
  window.__PTP_FIXTURE_DATA__=chosen; window.__PTP_TEST_CLIENT__=fakeSupabase(chosen);
})();`);
await page.route("https://fonts.googleapis.com/**",r=>r.fulfill({status:200,contentType:"text/css",body:""}));
await page.route("https://fonts.gstatic.com/**",r=>r.fulfill({status:200,body:""}));
await page.goto(base+"/camps/",{waitUntil:"load"});
await page.waitForTimeout(1200);
console.log("H1:", await page.textContent("#app h1, h1").catch(()=>"(none)"));
await b.close(); s.close();
